[package]
name = "pi_atom"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
fnv = "1.0.6"
lazy_static = "*"
pi_bon = {path="../pi_bon"}
pi_time = {path="../pi_time"}
pi_share = {path = "../pi_share"}
pi_hash = {path="../pi_hash", features = ["xxhash"]}

[dependencies.serde]
version = "1.0"
features = ["serde_derive"]
optional = true